### ISSUE TITLE
funsd上的训练效果

### ISSUE THREAD

**Issue by lying001209** [caop-kie/GraphRevisedIE#1]
您好我尝试在一些公共数据集如Funsd、SROIE上复现您的模型，但是效果并没有达到您论文中的效果。想询问下您在训练如funsd时，是否有做一些其他处理，如：1更换keys.txt为纯英文voc、2.documents.py里面MAX_BOXES_NUM 和MAX_TRANSCRIPT_LEN 的设定 3.GCN里面K的值的设定4.是否做了其他的前处理或者后处理

**Comment by caop-kie** [comment]
你好，感谢你的关注。关于你的问题，下面给出解释。
1. keys.txt只是用来得到one-hot encoding。
2. 开源的代码是针对营业执照这个数据集，你需要根据不同的数据集调整MAX_BOXES_NUM 和MAX_TRANSCRIPT_LEN。
3. GCN的K值需要根据不同的数据集进行调整。
4. SROIE存在OCR错误，你需要预处理它的错误数据。GraphRevisedIE是输出字符级别的标注，你需要后处理它的结果来得到词级别的标注。

**Comment by lying001209** [comment]
您好，非常感谢您的回复，您所做的工作非常棒，后续我会调整我的数据集并做一些后处理，重新进行实验，谢谢您的交流指导

**Comment by lying001209** [comment]
抱歉再问您一个问题，关于funsd训练集，您使用的是document.py 里面的哪种标注方法？

**Comment by caop-kie** [comment]
可以使用box_level。
